-- Generated by mssql_seed_export.py
-- Source database: AgilitySports_V2
-- Source table: [reference].[Sports]
-- Maximum rows per INSERT: 1000
-- Character literal mode: quoted

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    INSERT INTO [reference].[Sports] ([sportCode], [sportName])
    VALUES
        (N'MLB', N'Major League Baseball'),
        (N'NBA', N'National Basketball Association'),
        (N'NFL', N'National Football League'),
        (N'NHL', N'National Hockey League'),
        (N'PGA', N'Professional Golf Association'),
        (N'FIF', N'FIFA World Cup');

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;