-- Generated by mssql_seed_export.py
-- Source database: AgilitySports_V2
-- Source table: [reference].[PositionCodes]
-- Maximum rows per INSERT: 1000
-- Character literal mode: quoted

SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    INSERT INTO [reference].[PositionCodes] ([sportCode], [positionCode], [positionDesc])
    VALUES
        (N'MLB', N'1B', N'First Base'),
        (N'MLB', N'2B', N'Second Base'),
        (N'MLB', N'3B', N'Third Base'),
        (N'MLB', N'C', N'Catcher'),
        (N'MLB', N'CF', N'Center Field'),
        (N'MLB', N'DH', N'Designated Hitter'),
        (N'MLB', N'LF', N'Left Field'),
        (N'MLB', N'P', N'Pitcher'),
        (N'MLB', N'RF', N'Right Field'),
        (N'MLB', N'RP', N'Relief Pitcher'),
        (N'MLB', N'SP', N'Starting Pitcher'),
        (N'MLB', N'SS', N'Shortstop'),
        (N'NBA', N'C', N'Center'),
        (N'NBA', N'F', N'Forward'),
        (N'NBA', N'G', N'Guard'),
        (N'NBA', N'PF', N'Power Forward'),
        (N'NBA', N'PG', N'Point Guard'),
        (N'NBA', N'SF', N'Small Forward'),
        (N'NBA', N'SG', N'Shooting Guard'),
        (N'NFL', N'C', N'Center'),
        (N'NFL', N'CB', N'Cornerback'),
        (N'NFL', N'DB', N'Defensive Back'),
        (N'NFL', N'DE', N'Defensive End'),
        (N'NFL', N'DL', N'Defensive Lineman'),
        (N'NFL', N'DT', N'Defensive Tackle'),
        (N'NFL', N'FB', N'Fullback'),
        (N'NFL', N'G', N'Guard'),
        (N'NFL', N'ILB', N'Inside Linebacker'),
        (N'NFL', N'K', N'Kicker'),
        (N'NFL', N'LB', N'Linebacker'),
        (N'NFL', N'LS', N'Long Snapper'),
        (N'NFL', N'NT', N'Nose Tackle'),
        (N'NFL', N'OL', N'Offensive Lineman'),
        (N'NFL', N'OLB', N'Outside Linebacker'),
        (N'NFL', N'OT', N'Offensive Tackle'),
        (N'NFL', N'P', N'Punter'),
        (N'NFL', N'QB', N'Quarterback'),
        (N'NFL', N'RB', N'Running Back'),
        (N'NFL', N'S', N'Safety'),
        (N'NFL', N'TE', N'Tight End'),
        (N'NFL', N'WR', N'Wide Receiver'),
        (N'NHL', N'C', N'Center'),
        (N'NHL', N'D', N'Defenseman'),
        (N'NHL', N'F', N'Forward'),
        (N'NHL', N'G', N'Goalie'),
        (N'NHL', N'LW', N'Left Winger'),
        (N'NHL', N'RW', N'Right Winger'),
        (N'FIF', N'G', N'Goalkeeper'),
        (N'FIF', N'D', N'Defender'),
        (N'FIF', N'M', N'Midfielder'),
        (N'FIF', N'F', N'Forward'),
        (N'FIF', N'UNK', N'Unknown'),
        (N'PGA', N'G', N'Golfer'),
        (N'PGA', N'UNK', N'Unknown');

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
