/*
Purpose: Populate static lookup tables for AgilitySports.
Object: dbo.Sports,
Dependencies: Order is important.

Change Log:
2026-07-06  Initial version
*/

DELETE FROM dbo.Teams;
DELETE FROM dbo.PositionCodes;
DELETE FROM dbo.Sports;


INSERT INTO dbo.Sports (sportCode, sportName) VALUES
('MLB','Major League Baseball'),
('NBA','National Basketball Association'),
('NFL','National Football League'),
('NHL','National Hockey League'),
('PGA','Professional Golf Association');

print 'Done. ' + convert(varchar(10),@@rowcount) + ' rows inserted into dbo.Sports';

INSERT INTO [dbo].[PositionCodes] ([Sport], [PositionCode], [PositionDesc]) 
VALUES 
(N'NBA', N'C', N'Center'),
(N'NBA', N'F', N'Forward'),
(N'NBA', N'G', N'Guard'),
(N'NBA', N'PF', N'Power Forward'),
(N'NBA', N'PG', N'Point Guard'),
(N'NBA', N'SF', N'Small Forward'),
(N'NBA', N'SG', N'Shooting Guard'),
(N'NFL', N'C', N'Center'),
(N'NFL', N'CB', N'Cornerback'),
(N'NFL', N'DB', N'Defensive Back'),
(N'NFL', N'DE', N'Defensive End'),
(N'NFL', N'DL', N'Defensive Lineman'),
(N'NFL', N'DT', N'Defensive Tackle'),
(N'NFL', N'FB', N'Fullback'),
(N'NFL', N'G', N'Guard'),
(N'NFL', N'ILB', N'Inside Linebacker'),
(N'NFL', N'K', N'Kicker'),
(N'NFL', N'LB', N'Linebacker'),
(N'NFL', N'LS', N'Long Snapper'),
(N'NFL', N'NT', N'Nose Tackle'),
(N'NFL', N'OL', N'Offensive Lineman'),
(N'NFL', N'OLB', N'Outside Linebacker'),
(N'NFL', N'OT', N'Offensive Tackle'),
(N'NFL', N'P', N'Punter'),
(N'NFL', N'QB', N'Quarterback'),
(N'NFL', N'RB', N'Running Back'),
(N'NFL', N'S', N'Safety'),
(N'NFL', N'TE', N'Tight End'),
(N'NFL', N'WR', N'Wide Receiver'),
(N'NHL', N'C', N'Center'),
(N'NHL', N'D', N'Defenseman'),
(N'NHL', N'F', N'Forward'),
(N'NHL', N'G', N'Goalie'),
(N'NHL', N'LW', N'Left Winger'),
(N'NHL', N'RW', N'Right Winger')

print 'Done. ' + convert(varchar(10),@@rowcount) + ' rows inserted into dbo.PositionCodes';

INSERT INTO dbo.Teams(sportCode, teamCode, teamName, league)
VALUES
('NHL','Bruins','Boston Bruins','Eastern Atlantic'),
('NHL','Sabres','Buffalo Sabres','Eastern Atlantic'),
('NHL','Wings','Detroit Red Wings','Eastern Atlantic'),
('NHL','Panthers','Florida Panthers','Eastern Atlantic'),
('NHL','Canadiens','Montreal Canadiens','Eastern Atlantic'),
('NHL','Senators','Ottawa Senators','Eastern Atlantic'),
('NHL','Lightning','Tampa Bay Lightning','Eastern Atlantic'),
('NHL','Leafs','Toronto Maple Leafs','Eastern Atlantic'),
('NHL','Hurricanes','Carolina Hurricanes','Eastern Metropolitan'),
('NHL','Jackets','Columbus Blue Jackets','Eastern Metropolitan'),
('NHL','Devils','New Jersey Devils','Eastern Metropolitan'),
('NHL','Islanders','New York Islanders','Eastern Metropolitan'),
('NHL','Rangers','New York Rangers','Eastern Metropolitan'),
('NHL','Flyers','Philadelphia Flyers','Eastern Metropolitan'),
('NHL','Penguins','Pittsburgh Penguins','Eastern Metropolitan'),
('NHL','Capitals','Washington Capitals','Eastern Metropolitan'),
('NHL','Blackhawks','Chicago Blackhawks','Western Central'),
('NHL','Avalanche','Colorado Avalanche','Western Central'),
('NHL','Stars','Dallas Stars','Western Central'),
('NHL','Wild','Minnesota Wild','Western Central'),
('NHL','Predators','Nashville Predators','Western Central'),
('NHL','Blues','St. Louis Blues','Western Central'),
('NHL','Mammoth','Utah Mammoth','Western Central'),
('NHL','Jets','Winnipeg Jets','Western Central'),
('NHL','Ducks','Anaheim Ducks','Western Pacific'),
('NHL','Flames','Calgary Flames','Western Pacific'),
('NHL','Oilers','Edmonton Oilers','Western Pacific'),
('NHL','Kings','Los Angeles Kings','Western Pacific'),
('NHL','Sharks','San Jose Sharks','Western Pacific'),
('NHL','Kraken','Seattle Kraken','Western Pacific'),
('NHL','Canucks','Vancouver Canucks','Western Pacific'),
('NHL','Knights','Vegas Golden Knights','Western Pacific'),
('NBA','Celtics','Boston Celtics','Atlantic'),
('NBA','Nets','Brooklyn Nets','Atlantic'),
('NBA','Knicks','New York Knicks','Atlantic'),
('NBA','76ers','Philadelphia 76ers','Atlantic'),
('NBA','Raptors','Toronto Raptors','Atlantic'),
('NBA','Bulls','Chicago Bulls','Central'),
('NBA','Cavaliers','Cleveland Cavaliers','Central'),
('NBA','Pistons','Detroit Pistons','Central'),
('NBA','Pacers','Indiana Pacers','Central'),
('NBA','Bucks','Milwaukee Bucks','Central'),
('NBA','Hawks','Atlanta Hawks','Southeast'),
('NBA','Hornets','Charlotte Hornets','Southeast'),
('NBA','Heat','Miami Heat','Southeast'),
('NBA','Magic','Orlando Magic','Southeast'),
('NBA','Wizards','Washington Wizards','Southeast'),
('NBA','Nuggets','Denver Nuggets','Northwest'),
('NBA','Timberwolves','Minnesota Timberwolves','Northwest'),
('NBA','Thunder','Oklahoma City Thunder','Northwest'),
('NBA','Blazers','Portland Trail Blazers','Northwest'),
('NBA','Jazz','Utah Jazz','Northwest'),
('NBA','Warriors','Golden State Warriors','Pacific'),
('NBA','Clippers','LA Clippers','Pacific'),
('NBA','Lakers','Los Angeles Lakers','Pacific'),
('NBA','Suns','Phoenix Suns','Pacific'),
('NBA','Kings','Sacramento Kings','Pacific'),
('NBA','Mavericks','Dallas Mavericks','Southwest'),
('NBA','Rockets','Houston Rockets','Southwest'),
('NBA','Grizzlies','Memphis Grizzlies','Southwest'),
('NBA','Pelicans','New Orleans Pelicans','Southwest'),
('NBA','Spurs','San Antonio Spurs','Southwest'),
('NFL','Bills','Buffalo Bills','AFC East'),
('NFL','Dolphins','Miami Dolphins','AFC East'),
('NFL','Patriots','New England Patriots','AFC East'),
('NFL','Jets','New York Jets','AFC East'),
('NFL','Ravens','Baltimore Ravens','AFC North'),
('NFL','Bengals','Cincinnati Bengals','AFC North'),
('NFL','Browns','Cleveland Browns','AFC North'),
('NFL','Penguins','Pittsburgh Penguins','AFC North'),
('NFL','Texans','Houston Texans','AFC South'),
('NFL','Colts','Indianapolis Colts','AFC South'),
('NFL','Jaguars','Jacksonville Jaguars','AFC South'),
('NFL','Titans','Tennessee Titans','AFC South'),
('NFL','Broncos','Denver Broncos','AFC West'),
('NFL','Chiefs','Kansas City Chiefs','AFC West'),
('NFL','Raiders','Las Vegas Raiders','AFC West'),
('NFL','Chargers','Los Angeles Chargers','AFC West'),
('NFL','Cowboys','Dallas Cowboys','NFC East'),
('NFL','Giants','New York Giants','NFC East'),
('NFL','Eagles','Philadelphia Eagles','NFC East'),
('NFL','Commanders','Washington Commanders','NFC East'),
('NFL','Bears','Chicago Bears','NFC North'),
('NFL','Lions','Detroit Lions','NFC North'),
('NFL','Packers','Green Bay Packers','NFC North'),
('NFL','Vikings','Minnesota Vikings','NFC North'),
('NFL','Falcons','Atlanta Falcons','NFC South'),
('NFL','Panthers','Carolina Panthers','NFC South'),
('NFL','Saints','New Orleans Saints','NFC South'),
('NFL','Buccaneers','Tampa Bay Buccaneers','NFC South'),
('NFL','Cardinals','Arizona Cardinals','NFC West'),
('NFL','Rams','Los Angeles Rams','NFC West'),
('NFL','49ers','San Francisco 49ers','NFC West'),
('NFL','Seahawks','Seattle Seahawks','NFC West'),
('MLB','Orioles','Baltimore Orioles','American East'),
('MLB','Red Sox','Boston Red Sox','American East'),
('MLB','Yankees','New York Yankees','American East'),
('MLB','Rays','Tampa Bay Rays','American East'),
('MLB','Blue Jays','Toronto Blue Jays','American East'),
('MLB','White Sox','Chicago White Sox','American Central'),
('MLB','Guardians','Cleveland Guardians','American Central'),
('MLB','Tigers','Detroit Tigers','American Central'),
('MLB','Royals','Kansas City Royals','American Central'),
('MLB','Twins','Minnesota Twins','American Central'),
('MLB','Astros','Houston Astros','American West'),
('MLB','Angels','Los Angeles Angels','American West'),
('MLB','Athletics','Athletics','American West'),
('MLB','Mariners','Seattle Mariners','American West'),
('MLB','Rangers','Texas Rangers','American West'),
('MLB','Braves','Atlanta Braves','National East'),
('MLB','Marlins','Miami Marlins','National East'),
('MLB','Mets','New York Mets','National East'),
('MLB','Phillies','Philadelphia Phillies','National East'),
('MLB','Nationals','Washington Nationals','National East'),
('MLB','Cubs','Chicago Cubs','National Central'),
('MLB','Reds','Cincinnati Reds','National Central'),
('MLB','Brewers','Milwaukee Brewers','National Central'),
('MLB','Pirates','Pittsburgh Pirates','National Central'),
('MLB','Cardinals','St. Louis Cardinals','National Central'),
('MLB','Diamondbacks','Arizona Diamondbacks','National West'),
('MLB','Rockies','Colorado Rockies','National West'),
('MLB','Dodgers','Los Angeles Dodgers','National West'),
('MLB','Padres','San Diego Padres','National West'),
('MLB','Giants','San Francisco Giants','National West')

print 'Done. ' + convert(varchar(10),@@rowcount) + ' rows inserted into dbo.Teams';

