:r .\database\001-create-database.sql
:r .\security\002-security.sql
:r .\schema\101-ddl.V2.schemas.sql
:r .\schema\102-ddl.V2.Sports.sql
:r .\schema\103-ddl.V2.PositionsCodes.sql
:r .\schema\104-ddl.V2.Teams.sql
:r .\schema\105-ddl.V2.Players.sql
:r .\schema\106-ddl.V2.MLBPlayerStats.sql
:r .\schema\107-ddl.V2.NBAPlayerStats.sql
:r .\schema\108-ddl.V2.NFLPlayerStats.sql
:r .\schema\109-ddl.V2.NHLPlayerStats.sql
:r .\schema\115-ddl.V2.Attendance.sql
:r .\schema\120-sprocs.sql
:r .\seed\004-seed-common-data.sql
:r .\seed\005-seed-dev-data-NBA.sql
:r .\seed\006-seed-dev-data-NFL.sql
:r .\seed\007-seed-dev-data-NHL.sql
:r .\seed\008-seed-dev-data-MLB.sql
:r .\seed\009-seed-dev-data-PGA.sql
:r .\database\099-final-db-cleanup.sql
