IF EXISTS (SELECT 1 FROM [NHL].[Roster])
BEGIN
	PRINT 'NHL roster already seeded. Skipping 007-seed-dev-data-NHL.sql';
	SET NOEXEC ON;
END
GO

SET IDENTITY_INSERT [NHL].[Roster] ON 
GO
INSERT [NHL].[Roster] ([playerID], [Name], [Team], [Number], [Position], [Handed], [Age], [Drafted], [BirthPlace], [BirthCountry]) VALUES
(1, N'Jesper Docker', N'Bruins', N'70', N'C', N'L', 24, 2023, N'Docker, Universe', N'Sweden'),
(2, N'Patrick Brown', N'Bruins', N'38', N'C', N'R', 31, 2023, N'Bloomfield Hills, Michigan', N'United States'),
(3, N'Brandon Carlo', N'Bruins', N'25', N'D', N'R', 26, 2015, N'Colorado Springs, Colorado', N'United States'),
(4, N'Charlie Coyle', N'Bruins', N'13', N'C', N'R', 31, 2019, N'Weymouth, Massachusetts', N'United States'),
(5, N'Jake DeBrusk', N'Bruins', N'74', N'LW', N'L', 26, 2015, N'Edmonton, Alberta', N'Canada'),
(6, N'Derek Forbort', N'Bruins', N'28', N'D', N'L', 31, 2021, N'Duluth, Minnesota', N'United States'),
(7, N'Trent Frederic', N'Bruins', N'11', N'C', N'L', 25, 2016, N'St. Louis, Missouri', N'United States'),
(8, N'Morgan Geekie', N'Bruins', N'39', N'RW', N'R', 25, 2023, N'Strathclair, Manitoba', N'Canada'),
(9, N'JD Grierdrop', N'Bruins', N'13', N'LW', N'B', 33, 2011, N'nowhere', N'noplace'),
(10, N'Matt Grzelcyk', N'Bruins', N'48', N'D', N'L', 29, 2012, N'Charlestown, Massachusetts', N'United States'),
(11, N'string', N'string', N'111', N'C', N'R', 11, 0, N'string', N'<br>'),
(12, N'Mason Lohrei', N'Bruins', N'6', N'D', N'L', 22, 2020, N'Baton Rouge, Louisiana', N'United States'),
(13, N'Milan Lucic', N'Bruins', N'17', N'LW', N'L', 35, 2023, N'Vancouver, British Columbia', N'Canada'),
(14, N'Fabian Lysell', N'Bruins', N'23', N'RW', N'L', 20, 2021, N'Gothenburg, Sweden', N'Sweden'),
(15, N'Brad MarchandÂ (A)', N'Bruins', N'63', N'LW', N'L', 35, 2006, N'Halifax, Nova Scotia', N'Canada'),
(16, N'Charlie McAvoy', N'Bruins', N'73', N'D', N'R', 25, 2016, N'Long Beach, New York', N'United States'),
(17, N'Jayson Megna', N'Bruins', N'20', N'C', N'R', 33, 2023, N'Fort Lauderdale, Florida', N'United States'),
(18, N'Ian Mitchell', N'Bruins', N'14', N'D', N'R', 24, 2023, N'St. Albert, Alberta', N'Canada'),
(19, N'David Pastrnak', N'Bruins', N'88', N'RW', N'R', 27, 2014, N'HavÃ­Å™ov, Czech Republic', N'Czech Republic'),
(20, N'Alec Regula', N'Bruins', N'75', N'D', N'R', 23, 2023, N'West Bloomfield Township, Michigan', N'United States'),
(21, N'Anthony Richard', N'Bruins', N'90', N'C', N'L', 26, 2023, N'Trois-RiviÃ¨res, Quebec', N'Canada'),
(22, N'Kevin Shattenkirk', N'Bruins', N'12', N'D', N'R', 34, 2023, N'New Rochelle, New York', N'United States'),
(23, N'Jeremy Swayman', N'Bruins', N'1', N'G', N'L', 24, 2017, N'Anchorage, Alaska', N'United States'),
(24, N'Linus Ullmark', N'Bruins', N'35', N'G', N'L', 30, 2021, N'Lugnvik, Sweden', N'Sweden'),
(25, N'James van Riemsdyk', N'Bruins', N'21', N'LW', N'L', 34, 2023, N'Middletown Township, New Jersey', N'United States'),
(26, N'Pavel Zacha', N'Bruins', N'18', N'C', N'L', 26, 2022, N'Brno, Czech Republic', N'Czech Republic'),
(27, N'Jakub Zboril', N'Bruins', N'67', N'D', N'L', 26, 2015, N'Brno, Czech Republi', N'Czech Republic'),
(28, N'Jacob Bryson', N'Sabres', N'78', N'D', N'L', 25, 2017, N'London, Ontario', N'Canada'),
(29, N'Kale Clague', N'Sabres', N'38', N'D', N'L', 25, 2022, N'Regina, Saskatchewan', N'Canada'),
(30, N'Connor Clifton', N'Sabres', N'75', N'D', N'R', 28, 2023, N'Long Branch, New Jersey', N'United States'),
(31, N'Eric ComrieÂ ', N'Sabres', N'31', N'G', N'L', 28, 2022, N'Edmonton,Â Alberta', N'Canada'),
(32, N'Dylan Cozens', N'Sabres', N'24', N'C', N'R', 22, 2019, N'Whitehorse, Yukon', N'Injured Reserve'),
(33, N'Rasmus DahlinÂ (A)', N'Sabres', N'26', N'D', N'L', 23, 2018, N'Trollhattan, Sweden', N'Canada'),
(34, N'Zemgus GirgensonsÂ (A)', N'Sabres', N'28', N'C', N'L', 29, 2012, N'Riga, Latvia', N'Sweden'),
(35, N'Jordan Greenway', N'Sabres', N'12', N'LW', N'L', 26, 2023, N'Canton, New York', N'Latvia'),
(36, N'Erik Johnson', N'Sabres', N'6', N'D', N'R', 35, 2023, N'Bloomington, Minnesota', N'United States'),
(37, N'Henri Jokiharju', N'Sabres', N'10', N'D', N'R', 24, 2019, N'Oulu, Finland', N'United States'),
(38, N'Tyson Jost', N'Sabres', N'17', N'C', N'L', 25, 2022, N'St. Albert, Alberta', N'Finland'),
(39, N'Peyton Krebs', N'Sabres', N'19', N'C', N'L', 22, 2021, N'Okotoks, Alberta', N'Canada'),
(40, N'Devon Levi', N'Sabres', N'27', N'G', N'L', 21, 2021, N'Dollard-des-Ormeaux, Quebec', N'Canada'),
(41, N'Ukko-Pekka Luukkonen', N'Sabres', N'1', N'G', N'L', 24, 2017, N'Espoo, Finland', N'Canada'),
(42, N'Casey Mittelstadt', N'Sabres', N'37', N'C', N'L', 24, 2017, N'Eden Prairie, Minnesota', N'Finland'),
(43, N'Kyle OkposoÂ (C)', N'Sabres', N'21', N'RW', N'R', 35, 2016, N'Saint Paul, Minnesota', N'United States'),
(44, N'Victor Olofsson', N'Sabres', N'71', N'LW', N'L', 28, 2014, N'Ornskoldsvik, Sweden', N'United States'),
(45, N'JJ Peterka', N'Sabres', N'77', N'LW', N'L', 21, 2020, N'Munich, Germany', N'Sweden'),
(46, N'Owen Power', N'Sabres', N'25', N'D', N'L', 20, 2021, N'Mississauga, Ontario', N'Germany'),
(47, N'Jack QuinnÂ ', N'Sabres', N'22', N'RW', N'R', 21, 2020, N'Ottawa, Ontario', N'Canada'),
(48, N'Mattias SamuelssonÂ ', N'Sabres', N'23', N'D', N'L', 23, 2018, N'Voorhees, New Jersey', N'Canada'),
(49, N'Jeff Skinner', N'Sabres', N'53', N'LW', N'L', 31, 2018, N'Markham, Ontario', N'Injured Reserve'),
(50, N'Riley Stillman', N'Sabres', N'61', N'D', N'L', 25, 2023, N'Calgary, Alberta', N'United States'),
(51, N'Tage Thompson', N'Sabres', N'72', N'C', N'R', 25, 2018, N'Phoenix, Arizona', N'Injured Reserve'),
(52, N'Alex Tuch', N'Sabres', N'89', N'RW', N'R', 27, 2021, N'Syracuse, New York', N'Canada'),
(53, N'Jonatan Berggren', N'Red Wings', N'48', N'LW', N'L', 23, 2018, N'Uppsala, Sweden', N'Canada'),
(54, N'Ben Chiarot', N'Red Wings', N'8', N'D', N'L', 32, 2022, N'Hamilton, Ontario', N'United States'),
(55, N'Andrew Copp', N'Red Wings', N'18', N'C', N'L', 29, 2022, N'Ann Arbor, Michigan', N'United States'),
(56, N'J.T. Compher', N'Red Wings', N'37', N'C', N'R', 28, 2023, N'Northbrook, Illinois', N'Sweden'),
(57, N'Austin Czarnik', N'Red Wings', N'21', N'C', N'R', 30, 2022, N'Detroit, Michigan', N'Canada'),
(58, N'Alex DeBrincat', N'Red Wings', N'93', N'LW', N'R', 25, 2023, N'Farmington Hills, Michigan', N'United States'),
(59, N'Robby Fabbri', N'Red Wings', N'14', N'C', N'L', 27, 2019, N'Mississauga, Ontario', N'United States'),
(60, N'Christian Fischer', N'Red Wings', N'36', N'C', N'R', 26, 2023, N'Chicago, Illinois', N'United States'),
(61, N'Shayne Gostisbehere', N'Red Wings', N'41', N'D', N'L', 30, 2023, N'Pembroke Pines, Florida', N'United States'),
(62, N'Justin Holl', N'Red Wings', N'3', N'D', N'R', 31, 2023, N'Tonka Bay, Minnesota', N'Canada'),
(63, N'Ville Husso', N'Red Wings', N'35', N'G', N'L', 28, 2023, N'Helsinki, Finland', N'United States'),
(64, N'Marco Kasper', N'Red Wings', N'92', N'C', N'L', 19, 2022, N'Innsbruck,Â Austria', N'United States'),
(65, N'Klim Kostin', N'Red Wings', N'24', N'LW', N'L', 24, 2023, N'Penza, Russia', N'United States'),
(66, N'Dylan LarkinÂ (C)', N'Red Wings', N'71', N'C', N'L', 27, 2014, N'Waterford, Michigan', N'Finland'),
(67, N'Matt Luff', N'Red Wings', N'22', N'RW', N'R', 26, 2022, N'Oakville, Ontario', N'Austria'),
(68, N'Alex Lyon', N'Red Wings', N'34', N'G', N'L', 30, 2023, N'Baudette, Minnesota', N'Russia'),
(69, N'Olli Maatta', N'Red Wings', N'2', N'D', N'L', 29, 2022, N'Jyvaskyla, Finland', N'United States'),
(70, N'David Perron', N'Red Wings', N'57', N'LW', N'R', 35, 2022, N'Sherbrooke, Quebec', N'Canada'),
(71, N'Jeff Petry', N'Red Wings', N'46', N'D', N'R', 35, 2023, N'Ann Arbor, Michigan', N'United States'),
(72, N'Michael RasmussenÂ ', N'Red Wings', N'27', N'C', N'L', 24, 2017, N'Vancouver, British Columbia', N'Finland'),
(73, N'Lucas Raymond', N'Red Wings', N'23', N'LW', N'R', 21, 2020, N'Gothenburg, Sweden', N'Canada'),
(74, N'James Reimer', N'Red Wings', N'47', N'G', N'L', 35, 2023, N'Arborg, Manitoba', N'United States'),
(75, N'Moritz Seider', N'Red Wings', N'53', N'D', N'R', 22, 2019, N'Zell, Germany', N'Canada'),
(76, N'Daniel Sprong', N'Red Wings', N'88', N'RW', N'R', 26, 2023, N'Amsterdam, Netherlands', N'Injured Reserve'),
(77, N'Joe Veleno', N'Red Wings', N'90', N'C', N'L', 23, 2018, N'Montreal, Quebec', N'Sweden'),
(78, N'Jake Walman', N'Red Wings', N'96', N'D', N'L', 27, 2022, N'Toronto, Ontario', N'Canada'),
(79, N'Aleksander BarkovÂ (C)', N'Panthers', N'16', N'C', N'L', 27, 2013, N'Tampere, Finland', N'Germany'),
(80, N'Sam Bennett', N'Panthers', N'9', N'C', N'L', 27, 2021, N'East Gwillimbury, Ontario', N'Netherlands'),
(81, N'Mike Benning', N'Panthers', N'44', N'D', N'R', 21, 2020, N'Edmonton,Â Alberta', N'Canada'),
(82, N'Sergei Bobrovsky', N'Panthers', N'72', N'G', N'L', 34, 2019, N'Novokuznetsk, Soviet Union', N'Canada'),
(83, N'Lucas Carlsson', N'Panthers', N'32', N'D', N'L', 26, 2021, N'GÃ¤vle, Sweden', N'Finland'),
(84, N'Nick Cousins', N'Panthers', N'21', N'C', N'L', 30, 2022, N'Belleville, Ontario', N'Canada'),
(85, N'Zac Dalpe', N'Panthers', N'22', N'C', N'R', 33, 2021, N'Paris, Ontario', N'Canada'),
(86, N'Grigori Denisenko', N'Panthers', N'14', N'RW', N'R', 23, 2018, N'Novosibirsk, Russia', N'Russia'),
(87, N'Aaron EkbladÂ (A)', N'Panthers', N'5', N'D', N'R', 27, 2014, N'Windsor, Ontario', N'Sweden'),
(88, N'Oliver Ekman-Larsson', N'Panthers', N'91', N'D', N'L', 32, 2023, N'Karlskrona, Sweden', N'Canada'),
(89, N'Casey Fitzgerald', N'Panthers', N'4', N'D', N'R', 26, 2023, N'Boca Raton, Florida', N'Canada'),
(90, N'Gustav Forsling', N'Panthers', N'42', N'D', N'L', 27, 2021, N'LinkÃ¶ping, Sweden', N'Russia'),
(91, N'Patrick Giles', N'Panthers', N'36', N'C', N'R', 23, 2022, N'Chevy Chase, Maryland', N'Canada'),
(92, N'Mack Guzda', N'Panthers', N'29', N'G', N'L', 22, 2022, N'Knoxville, Tennessee', N'Sweden'),
(93, N'Matt Kiersted', N'Panthers', N'3', N'D', N'L', 25, 2021, N'Elk River, Minnesota', N'United States'),
(94, N'Santtu Kinnunen', N'Panthers', N'75', N'D', N'R', 24, 2018, N'Lahti,Â Finland', N'Sweden'),
(95, N'Spencer Knight', N'Panthers', N'30', N'G', N'L', 22, 2019, N'Darien, Connecticut', N'United States'),
(96, N'Dmitry Kulikov', N'Panthers', N'7', N'D', N'L', 32, 2023, N'Lipetsk,Â Soviet Union', N'United States'),
(97, N'Ryan Lomberg', N'Panthers', N'94', N'LW', N'L', 28, 2021, N'Richmond Hill, Ontario', N'United States'),
(98, N'Steven Lorentz', N'Panthers', N'18', N'LW', N'L', 27, 2023, N'Kitchener, Ontario', N'Finland'),
(99, N'John Ludvig', N'Panthers', N'53', N'D', N'L', 23, 2019, N'Liberec, Czech Republic', N'United States'),
(100, N'Anton Lundell', N'Panthers', N'15', N'C', N'L', 21, 2020, N'Espoo, Finland', N'Russia'),
(101, N'Eetu Luostarinen', N'Panthers', N'27', N'C', N'L', 25, 2020, N'SiilinjÃ¤rvi, Finland', N'Canada'),
(102, N'Josh Mahura', N'Panthers', N'28', N'D', N'L', 25, 2022, N'St. Albert, Alberta', N'Canada'),
(103, N'Niko Mikkola', N'Panthers', N'77', N'D', N'L', 27, 2023, N'Kiiminki,Â Finland', N'Canada'),
(104, N'Brandon Montour', N'Panthers', N'62', N'D', N'R', 29, 2021, N'Ohsweken, Ontario', N'Finland'),
(105, N'Mike Reilly', N'Panthers', N'6', N'D', N'L', 30, 2023, N'Chicago, Illinois', N'Finland'),
(106, N'Sam Reinhart', N'Panthers', N'13', N'C', N'R', 27, 2021, N'North Vancouver, British Columbia', N'Canada'),
(107, N'Evan Rodrigues', N'Panthers', N'17', N'C', N'R', 30, 2023, N'Toronto, Ontario', N'Finland'),
(108, N'Calle Sjalin', N'Panthers', N'79', N'D', N'L', 24, 2022, N'Ã–stersund,Â Sweden', N'Canada'),
(109, N'Kevin Stenlund', N'Panthers', N'82', N'C', N'L', 26, 2023, N'Stockholm, Sweden', N'United States'),
(110, N'Anthony Stolarz', N'Panthers', N'41', N'G', N'L', 29, 2023, N'Edison, New Jersey', N'Canada'),
(111, N'Matthew TkachukÂ (A)', N'Panthers', N'19', N'LW', N'L', 25, 2022, N'Scottsdale, Arizona', N'Canada'),
(112, N'Carter Verhaeghe', N'Panthers', N'23', N'C', N'L', 28, 2020, N'Toronto, Ontario', N'Sweden'),
(113, N'Jake Allen', N'Canadiens', N'34', N'G', N'L', 33, 2020, N'Fredericton, New Brunswick', N'Sweden'),
(114, N'Josh Anderson', N'Canadiens', N'17', N'RW', N'R', 29, 2020, N'Burlington, Ontario', N'United States'),
(115, N'Joel Armia', N'Canadiens', N'40', N'RW', N'R', 30, 2018, N'Pori, Finland', N'United States'),
(116, N'Justin Barron', N'Canadiens', N'52', N'D', N'R', 21, 2022, N'Halifax, Nova Scotia', N'Canada'),
(117, N'Cole CaufieldÂ ', N'Canadiens', N'22', N'RW', N'R', 22, 2019, N'Mosinee, Wisconsin', N'Canada'),
(118, N'Kirby Dach', N'Canadiens', N'77', N'C', N'R', 22, 2022, N'St. Albert, Alberta', N'Canada'),
(119, N'Casey DeSmith', N'Canadiens', N'â€“', N'G', N'L', 32, 2023, N'Rochester, New Hampshire', N'Finland'),
(120, N'Christian Dvorak', N'Canadiens', N'28', N'C', N'L', 27, 2021, N'Palos, Illinois', N'Canada'),
(121, N'Jake Evans', N'Canadiens', N'71', N'C', N'R', 27, 2014, N'Toronto, Ontario', N'United States'),
(122, N'Sean Farrell', N'Canadiens', N'57', N'C', N'L', 21, 2020, N'Milton, Massachusetts', N'Injured Reserve'),
(123, N'Brendan GallagherÂ (A)', N'Canadiens', N'11', N'RW', N'R', 31, 2010, N'Edmonton, Alberta', N'Canada'),
(124, N'Kaiden Guhle', N'Canadiens', N'21', N'D', N'L', 21, 2020, N'Edmonton, Alberta', N'United States'),
(125, N'Jordan Harris', N'Canadiens', N'54', N'D', N'L', 23, 2018, N'Haverhill, Massachusetts', N'United States'),
(126, N'Rafael Harvey-Pinard', N'Canadiens', N'49', N'LW', N'L', 24, 2019, N'Saguenay, Quebec', N'Canada'),
(127, N'Johnathan Kovacevic', N'Canadiens', N'26', N'D', N'R', 26, 2022, N'Niagara Falls, Ontario', N'United States'),
(128, N'Gustav Lindstrom', N'Canadiens', N'â€“', N'D', N'R', 24, 2023, N'Ostervala, Sweden', N'Canada'),
(129, N'Mike Matheson', N'Canadiens', N'8', N'D', N'L', 29, 2022, N'Pointe-Claire, Quebec', N'Canada'),
(130, N'Sean MonahanÂ ', N'Canadiens', N'91', N'C', N'L', 28, 2022, N'Brampton, Ontario', N'United States'),
(131, N'Sam Montembeault', N'Canadiens', N'35', N'G', N'L', 26, 2021, N'BÃ©cancour, Quebec', N'Canada'),
(132, N'Alex Newhook', N'Canadiens', N'15', N'C', N'L', 22, 2023, N'St. John''s, Newfoundland', N'Canada'),
(133, N'Michael Pezzetta', N'Canadiens', N'55', N'LW', N'L', 25, 2016, N'Toronto, Ontario', N'Sweden'),
(134, N'Carey PriceÂ ', N'Canadiens', N'31', N'G', N'L', 36, 2005, N'Anahim Lake, British Columbia', N'Canada'),
(135, N'David Savard', N'Canadiens', N'58', N'D', N'R', 32, 2021, N'Saint-Hyacinthe, Quebec', N'Canada'),
(136, N'Juraj SlafkovskyÂ ', N'Canadiens', N'20', N'LW', N'L', 19, 2022, N'KoÅ¡ice, Slovakia', N'Injured Reserve'),
(137, N'Nick SuzukiÂ (C)', N'Canadiens', N'14', N'C', N'R', 24, 2018, N'London, Ontario', N'Canada'),
(138, N'Chris Wideman', N'Canadiens', N'6', N'D', N'R', 33, 2021, N'St. Louis, Missouri', N'Canada'),
(139, N'Arber XhekajÂ ', N'Canadiens', N'72', N'D', N'L', 22, 2021, N'Hamilton, Ontario', N'Canada'),
(140, N'Drake Batherson', N'Senators', N'19', N'RW', N'R', 25, 2017, N'Fort Wayne, Indiana', N'Canada'),
(141, N'Jacob Bernard-Docker', N'Senators', N'24', N'D', N'R', 23, 2018, N'Canmore, Alberta', N'Injured Reserve'),
(142, N'Erik Brannstrom', N'Senators', N'26', N'D', N'L', 24, 2019, N'EksjÃ¶, Sweden', N'Canada'),
(143, N'Thomas ChabotÂ (A)', N'Senators', N'72', N'D', N'L', 26, 2015, N'Sainte-Marie, Quebec', N'Slovakia'),
(144, N'Jakob Chychrun', N'Senators', N'6', N'D', N'L', 25, 2023, N'Boca Raton, Florida', N'Injured Reserve'),
(145, N'Anton ForsbergÂ ', N'Senators', N'31', N'G', N'L', 30, 2021, N'HÃ¤rnÃ¶sand, Sweden', N'Canada'),
(146, N'Claude GirouxÂ (A)', N'Senators', N'28', N'RW', N'R', 35, 2022, N'Hearst, Ontario', N'United States'),
(147, N'Travis Hamonic', N'Senators', N'23', N'D', N'R', 33, 2022, N'St. Malo, Manitoba', N'Canada'),
(148, N'Mathieu Joseph', N'Senators', N'21', N'RW', N'L', 26, 2022, N'Laval, Quebec', N'Injured Reserve'),
(149, N'Mark Kastelic', N'Senators', N'12', N'C', N'R', 24, 2019, N'Phoenix, Arizona', N'Canada'),
(150, N'Parker Kelly', N'Senators', N'27', N'C', N'L', 24, 2021, N'Camrose, Alberta', N'Canada'),
(151, N'Tyler Kleven', N'Senators', N'43', N'D', N'L', 21, 2020, N'Fargo, North Dakota', N'Sweden'),
(152, N'Joonas Korpisalo', N'Senators', N'70', N'G', N'L', 29, 2023, N'Pori, Finland', N'Canada'),
(153, N'Dominik Kubalik', N'Senators', N'81', N'LW', N'L', 28, 2023, N'Plzen, Czech Republic', N'Canada'),
(154, N'Zack MacEwen', N'Senators', N'17', N'RW', N'R', 27, 2023, N'Charlottetown, Prince Edward Island', N'Sweden'),
(155, N'Josh NorrisÂ ', N'Senators', N'9', N'C', N'L', 24, 2018, N'Oxford, Michigan', N'Injured Reserve'),
(156, N'Shane PintoÂ (RFA)', N'Senators', N'57', N'C', N'R', 22, 2019, N'Franklin Square, New York', N'Canada'),
(157, N'Jake Sanderson', N'Senators', N'85', N'D', N'L', 21, 2020, N'Whitefish, Montana', N'Canada'),
(158, N'Tim Stuetzle', N'Senators', N'18', N'LW', N'L', 21, 2020, N'Viersen, Germany', N'Canada'),
(159, N'Vladimir Tarasenko', N'Senators', N'91', N'RW', N'L', 31, 2023, N'Yaroslavl, Soviet Union', N'United States'),
(160, N'Brady TkachukÂ (C)', N'Senators', N'7', N'LW', N'L', 23, 2018, N'Scottsdale, Arizona', N'Canada'),
(161, N'Artyom Zub', N'Senators', N'2', N'D', N'R', 27, 2020, N'Khabarovsk, Russia', N'United States'),
(162, N'Josh Archibald', N'Lightening', N'â€“', N'RW', N'R', 30, 2023, N'Regina, Saskatchewan', N'Finland'),
(163, N'Zach Bogosian', N'Lightening', N'24', N'D', N'R', 33, 2021, N'Massena, New York', N'Czech Republic'),
(164, N'Logan Brown', N'Lightening', N'â€“', N'C', N'L', 25, 2023, N'Raleigh, North Carolina', N'Canada'),
(165, N'Erik CernakÂ ', N'Lightening', N'81', N'D', N'R', 26, 2017, N'KoÅ¡ice, Slovakia', N'United States'),
(166, N'Anthony Cirelli', N'Lightening', N'71', N'C', N'L', 26, 2015, N'Woodbridge, Ontario', N'Injured Reserve'),
(167, N'Calvin de Haan', N'Lightening', N'â€“', N'D', N'L', 32, 2023, N'Carp, Ontario', N'United States'),
(168, N'Mikey Eyssimont', N'Lightening', N'23', N'LW', N'L', 27, 2023, N'Littleton, Colorado', N'United States'),
(169, N'Haydn Fleury', N'Lightening', N'7', N'D', N'L', 27, 2022, N'Carlyle, Saskatchewan', N'Germany'),
(170, N'Luke Glendening', N'Lightening', N'â€“', N'C', N'R', 34, 2023, N'East Grand Rapids, Michigan', N'Russia'),
(171, N'Brandon Hagel', N'Lightening', N'38', N'LW', N'L', 25, 2022, N'Saskatoon, Saskatchewan', N'United States'),
(172, N'Victor HedmanÂ (A)', N'Lightening', N'77', N'D', N'L', 32, 2009, N'Ã–rnskÃ¶ldsvik, Sweden', N'Russia'),
(173, N'Tanner Jeannot', N'Lightening', N'84', N'LW', N'L', 26, 2023, N'Oxbow, Saskatchewan', N'Canada'),
(174, N'Jonas Johansson', N'Lightening', N'â€“', N'G', N'L', 27, 2023, N'GÃ¤vle,Â Sweden', N'United States'),
(175, N'Nikita Kucherov', N'Lightening', N'86', N'RW', N'L', 30, 2011, N'Maykop, Russia', N'United States'),
(176, N'Tyler Motte', N'Lightening', N'14', N'C', N'L', 28, 2023, N'Port Huron, Michigan', N'Slovakia'),
(177, N'Nick Paul', N'Lightening', N'20', N'LW', N'L', 28, 2022, N'Mississauga, Ontario', N'Injured Reserve'),
(178, N'Nick Perbix', N'Lightening', N'48', N'D', N'R', 25, 2017, N'Elk River, Minnesota', N'Canada'),
(179, N'Brayden Point', N'Lightening', N'21', N'C', N'R', 27, 2014, N'Calgary, Alberta', N'Canada'),
(180, N'Darren Raddysh', N'Lightening', N'43', N'D', N'R', 27, 2021, N'Caledon, Ontario', N'United States'),
(181, N'Mikhail Sergachev', N'Lightening', N'98', N'D', N'L', 25, 2017, N'Nizhnekamsk, Russia', N'Canada'),
(182, N'Conor Sheary', N'Lightening', N'â€“', N'LW', N'L', 31, 2023, N'Winchester, Massachusetts', N'United States'),
(183, N'Steven StamkosÂ (C)', N'Lightening', N'91', N'C', N'R', 33, 2008, N'Markham, Ontario', N'Canada'),
(184, N'Andrei Vasilevskiy', N'Lightening', N'88', N'G', N'L', 28, 2012, N'Tyumen, Russia', N'Sweden'),
(185, N'Simon Benoit', N'Maple Leafs', N'â€“', N'D', N'L', 24, 2023, N'Laval, Quebec', N'Canada'),
(186, N'Tyler Bertuzzi', N'Maple Leafs', N'59', N'LW', N'L', 28, 2023, N'Sudbury, Ontario', N'Sweden'),
(187, N'T. J. Brodie', N'Maple Leafs', N'78', N'D', N'L', 33, 2020, N'Chatham, Ontario', N'Russia'),
(188, N'Max Domi', N'Maple Leafs', N'11', N'LW', N'L', 28, 2023, N'Winnipeg, Manitoba', N'United States'),
(189, N'Dylan Gambrell', N'Maple Leafs', N'â€“', N'C', N'R', 27, 2023, N'Bonney Lake, Washington', N'Canada'),
(190, N'Mark Giordano', N'Maple Leafs', N'55', N'D', N'L', 39, 2022, N'Toronto, Ontario', N'United States'),
(191, N'Calle Jarnkrok', N'Maple Leafs', N'19', N'RW', N'R', 31, 2022, N'GÃ¤vle, Sweden', N'Canada'),
(192, N'Martin Jones', N'Maple Leafs', N'â€“', N'G', N'L', 33, 2023, N'North Vancouver, British Columbia', N'Canada'),
(193, N'David Kampf', N'Maple Leafs', N'64', N'C', N'L', 28, 2021, N'Jirkov, Czech Republic', N'Russia'),
(194, N'John Klingberg', N'Maple Leafs', N'3', N'D', N'R', 31, 2023, N'Gothenburg, Sweden', N'United States'),
(195, N'Matthew Knies', N'Maple Leafs', N'23', N'LW', N'L', 20, 2021, N'Phoenix, Arizona', N'Canada'),
(196, N'Sam Lafferty', N'Maple Leafs', N'28', N'C', N'R', 28, 2023, N'Hollidaysburg, Pennsylvania', N'Russia'),
(197, N'Timothy Liljegren', N'Maple Leafs', N'37', N'D', N'R', 24, 2017, N'Kristianstad, Sweden', N'Canada'),
(198, N'Mitch MarnerÂ (A)', N'Maple Leafs', N'16', N'RW', N'R', 26, 2015, N'Markham, Ontario', N'Canada'),
(199, N'Auston MatthewsÂ (A)', N'Maple Leafs', N'34', N'C', N'L', 25, 2016, N'San Ramon, California', N'Canada'),
(200, N'Jake McCabe', N'Maple Leafs', N'22', N'D', N'L', 29, 2023, N'Eau Claire, Wisconsin', N'Canada'),
(201, N'Bobby McMann', N'Maple Leafs', N'74', N'C', N'L', 27, 2022, N'Wainwright, Alberta', N'United States'),
(202, N'Matt MurrayÂ ', N'Maple Leafs', N'30', N'G', N'L', 29, 2022, N'Thunder Bay, Ontario', N'Canada'),
(203, N'Jake MuzzinÂ (A)Â ', N'Maple Leafs', N'8', N'D', N'L', 34, 2019, N'Woodstock, Ontario', N'Sweden'),
(204, N'William Nylander', N'Maple Leafs', N'88', N'RW', N'R', 27, 2014, N'Calgary, Alberta', N'Canada'),
(205, N'Ryan Reaves', N'Maple Leafs', N'75', N'RW', N'R', 36, 2023, N'Winnipeg, Manitoba', N'Czech Republic'),
(206, N'Morgan RiellyÂ (A)', N'Maple Leafs', N'44', N'D', N'L', 29, 2012, N'West Vancouver, British Columbia', N'Sweden'),
(207, N'Nicholas RobertsonÂ ', N'Maple Leafs', N'89', N'LW', N'L', 21, 2019, N'Arcadia, California', N'United States'),
(208, N'Ilya Samsonov', N'Maple Leafs', N'35', N'G', N'L', 26, 2022, N'Magnitogorsk, Russia', N'United States'),
(209, N'John TavaresÂ (C)', N'Maple Leafs', N'91', N'C', N'L', 32, 2018, N'Mississauga, Ontario', N'Sweden'),
(210, N'Conor Timmins', N'Maple Leafs', N'25', N'D', N'R', 24, 2022, N'St. Catharines, Ontario', N'Canada'),
(211, N'Sebastian AhoÂ (A)', N'Hurricanes', N'20', N'C', N'L', 26, 2015, N'Rauma, Finland', N'United States'),
(212, N'Frederik Andersen', N'Hurricanes', N'31', N'G', N'L', 33, 2021, N'Herning, Denmark', N'United States'),
(213, N'Nathan BeaulieuÂ (PTO)', N'Hurricanes', N'â€“', N'D', N'L', 30, 2023, N'Strathroy, Ontario', N'Canada'),
(214, N'Michael Bunting', N'Hurricanes', N'58', N'LW', N'L', 27, 2023, N'Scarborough, Ontario', N'Canada'),
(215, N'Brent Burns', N'Hurricanes', N'8', N'D', N'R', 38, 2022, N'Barrie, Ontario', N'Injured Reserve'),
(216, N'Jalen Chatfield', N'Hurricanes', N'5', N'D', N'R', 27, 2021, N'Ypsilanti, Michigan', N'Canada'),
(217, N'Dylan Coghlan', N'Hurricanes', N'15', N'D', N'R', 25, 2022, N'Duncan, British Columbia', N'Injured Reserve'),
(218, N'Tony DeAngelo', N'Hurricanes', N'77', N'D', N'R', 27, 2023, N'Sewell, New Jersey', N'Sweden'),
(219, N'Jack Drury', N'Hurricanes', N'18', N'C', N'L', 23, 2018, N'New York, New York', N'Canada'),
(220, N'Jesper Fast', N'Hurricanes', N'71', N'RW', N'R', 31, 2020, N'NÃ¤ssjÃ¶, Sweden', N'Canada'),
(221, N'Jake GardinerÂ ', N'Hurricanes', N'51', N'D', N'L', 33, 2019, N'Minneapolis, Minnesota', N'United States'),
(222, N'Seth Jarvis', N'Hurricanes', N'24', N'C', N'R', 21, 2020, N'Winnipeg, Manitoba', N'Injured Reserve'),
(223, N'Caleb Jones', N'Hurricanes', N'â€“', N'D', N'L', 26, 2023, N'Arlington, Texas', N'Russia'),
(224, N'Pyotr Kochetkov', N'Hurricanes', N'52', N'G', N'L', 24, 2019, N'Penza, Russia', N'Canada'),
(225, N'Jesperi Kotkaniemi', N'Hurricanes', N'82', N'C', N'L', 23, 2021, N'Pori, Finland', N'Canada'),
(226, N'Brendan Lemieux', N'Hurricanes', N'28', N'LW', N'L', 27, 2023, N'Denver, Colorado', N'Finland'),
(227, N'Jordan MartinookÂ (A)', N'Hurricanes', N'48', N'LW', N'L', 31, 2018, N'Brandon, Manitoba', N'Denmark'),
(228, N'Martin Necas', N'Hurricanes', N'88', N'C', N'R', 24, 2017, N'NovÃ© MÄ›sto na MoravÄ›, Czech Republic', N'Canada'),
(229, N'Stefan Noesen', N'Hurricanes', N'23', N'RW', N'R', 30, 2021, N'Plano, Texas', N'Canada'),
(230, N'Dmitry Orlov', N'Hurricanes', N'7', N'D', N'L', 32, 2023, N'Novokuznetsk, Soviet Union', N'Canada'),
(231, N'Brett Pesce', N'Hurricanes', N'22', N'D', N'R', 28, 2013, N'Tarrytown, New York', N'United States'),
(232, N'Vasily Ponomarev', N'Hurricanes', N'92', N'C', N'L', 21, 2020, N'Moscow,Â Russia', N'Canada'),
(233, N'Antti Raanta', N'Hurricanes', N'32', N'G', N'L', 34, 2021, N'Rauma, Finland', N'United States'),
(234, N'Jamieson Rees', N'Hurricanes', N'81', N'C', N'L', 22, 2019, N'Hamilton, Ontario', N'United States'),
(235, N'Brady Skjei', N'Hurricanes', N'76', N'D', N'L', 29, 2020, N'Lakeville, Minnesota', N'Sweden'),
(236, N'Jaccob SlavinÂ (A)', N'Hurricanes', N'74', N'D', N'L', 29, 2012, N'Erie, Colorado', N'United States'),
(237, N'Jordan StaalÂ (C)', N'Hurricanes', N'11', N'C', N'L', 35, 2012, N'Thunder Bay, Ontario', N'Injured Reserve'),
(238, N'Ryan Suzuki', N'Hurricanes', N'61', N'C', N'L', 22, 2019, N'London, Ontario', N'Canada'),
(239, N'Andrei SvechnikovÂ ', N'Hurricanes', N'37', N'RW', N'L', 23, 2018, N'Barnaul, Russia', N'United States'),
(240, N'Teuvo TeravainenÂ ', N'Hurricanes', N'86', N'LW', N'L', 28, 2016, N'Helsinki, Finland', N'Russia'),
(241, N'Jake BeanÂ ', N'Blue Jackets', N'22', N'D', N'L', 25, 2021, N'Calgary, Alberta', N'Finland'),
(242, N'Emil Bemstrom', N'Blue Jackets', N'52', N'RW', N'R', 24, 2017, N'NykÃ¶ping, Sweden', N'Canada'),
(243, N'Tim BerniÂ (RFA)', N'Blue Jackets', N'75', N'D', N'L', 23, 2018, N'MÃ¤nnedorf, Switzerland', N'Canada'),
(244, N'Marcus Bjork', N'Blue Jackets', N'47', N'D', N'R', 25, 2022, N'UmeÃ¥, Sweden', N'Czech Republic'),
(245, N'Nick Blankenburg', N'Blue Jackets', N'77', N'D', N'R', 25, 2022, N'Washington, Michigan', N'United States'),
(246, N'Adam Boqvist', N'Blue Jackets', N'27', N'D', N'R', 23, 2021, N'Falun, Sweden', N'Russia'),
(247, N'Justin DanforthÂ ', N'Blue Jackets', N'17', N'RW', N'R', 30, 2021, N'Oshawa, Ontario', N'United States'),
(248, N'Adam Fantilli', N'Blue Jackets', N'11', N'C', N'L', 18, 2023, N'Nobleton, Ontario', N'Russia'),
(249, N'Liam Foudy', N'Blue Jackets', N'19', N'C', N'L', 23, 2018, N'Toronto, Ontario', N'Finland'),
(250, N'Johnny Gaudreau', N'Blue Jackets', N'13', N'LW', N'L', 30, 2022, N'Salem, New Jersey', N'Canada'),
(251, N'Erik GudbransonÂ ', N'Blue Jackets', N'44', N'D', N'R', 31, 2022, N'Ottawa, Ontario', N'United States'),
(252, N'Boone JennerÂ (C)', N'Blue Jackets', N'38', N'C', N'L', 30, 2011, N'London, Ontario', N'United States'),
(253, N'Kent Johnson', N'Blue Jackets', N'91', N'C', N'L', 20, 2021, N'Port Moody, British Columbia', N'Canada'),
(254, N'Sean KuralyÂ ', N'Blue Jackets', N'7', N'C', N'L', 30, 2021, N'Dublin, Ohio', N'Canada'),
(255, N'Patrik LaineÂ ', N'Blue Jackets', N'29', N'RW', N'R', 25, 2021, N'Tampere, Finland', N'Russia'),
(256, N'Kirill Marchenko', N'Blue Jackets', N'86', N'RW', N'R', 23, 2018, N'Barnaul, Russia', N'Injured Reserve'),
(257, N'Hunter McKown', N'Blue Jackets', N'41', N'C', N'R', 21, 2023, N'San Jose, California', N'Finland'),
(258, N'Elvis Merzlikins', N'Blue Jackets', N'90', N'G', N'L', 29, 2014, N'Riga, Latvia', N'Injured Reserve'),
(259, N'Mathieu Olivier', N'Blue Jackets', N'24', N'RW', N'R', 26, 2022, N'Biloxi, Mississippi', N'Canada'),
(260, N'Andrew Peeke', N'Blue Jackets', N'2', N'D', N'R', 25, 2016, N'Parkland, Florida', N'Injured Reserve'),
(261, N'Ivan Provorov', N'Blue Jackets', N'9', N'D', N'L', 26, 2023, N'Yaroslavl, Russia', N'Sweden'),
(262, N'Eric Robinson', N'Blue Jackets', N'50', N'LW', N'L', 28, 2018, N'Bellmawr, New Jersey', N'Switzerland'),
(263, N'Jack Roslovic', N'Blue Jackets', N'96', N'C', N'R', 26, 2021, N'Columbus, Ohio', N'Sweden'),
(264, N'Damon Severson', N'Blue Jackets', N'78', N'D', N'R', 29, 2023, N'Brandon, Manitoba', N'United States'),
(265, N'Alexandre Texier', N'Blue Jackets', N'42', N'C', N'L', 23, 2017, N'Grenoble, France', N'Sweden'),
(266, N'Zach WerenskiÂ (A)Â ', N'Blue Jackets', N'8', N'D', N'L', 26, 2015, N'Grosse Pointe, Michigan', N'Canada'),
(267, N'Kevin Bahl', N'Devils', N'88', N'D', N'L', 23, 2019, N'New Westminster, British Columbia', N'Injured Reserve'),
(268, N'Nathan Bastian', N'Devils', N'14', N'RW', N'R', 25, 2021, N'Kitchener, Ontario', N'Canada'),
(269, N'Jesper Bratt', N'Devils', N'63', N'LW', N'L', 25, 2017, N'Stockholm, Sweden', N'Canada'),
(270, N'Graeme Clarke', N'Devils', N'92', N'RW', N'R', 22, 2019, N'Waconia, Minnesota', N'United States'),
(271, N'Nico Daws', N'Devils', N'50', N'G', N'L', 21, 2020, N'Munich, Germany', N'Canada'),
(272, N'Cal Foote', N'Devils', N'52', N'D', N'R', 24, 2023, N'Englewood, Colorado', N'Injured Reserve'),
(273, N'Nolan Foote', N'Devils', N'25', N'LW', N'L', 22, 2020, N'Englewood, Colorado', N'Canada'),
(274, N'Brian Halonen', N'Devils', N'48', N'LW', N'R', 24, 2022, N'Delano, Minnesota', N'Canada'),
(275, N'Dougie Hamilton', N'Devils', N'7', N'D', N'R', 30, 2021, N'Toronto, Ontario', N'United States'),
(276, N'Erik Haula', N'Devils', N'56', N'LW', N'L', 32, 2022, N'Pori, Finland', N'Injured Reserve'),
(277, N'Nico HischierÂ (C)', N'Devils', N'13', N'C', N'L', 24, 2017, N'Brig, Switzerland', N'Finland'),
(278, N'Alexander Holtz', N'Devils', N'10', N'F', N'L', 21, 2020, N'SaltsjÃ¶-Boo, Sweden', N'Injured Reserve'),
(279, N'Jack HughesÂ (A)', N'Devils', N'86', N'C', N'L', 22, 2019, N'Orlando, Florida', N'Russia'),
(280, N'Luke Hughes', N'Devils', N'43', N'D', N'L', 20, 2021, N'Manchester, New Hampshire', N'United States'),
(281, N'Curtis Lazar', N'Devils', N'42', N'C', N'R', 28, 2023, N'Salmon Arm, British Columbia', N'Latvia'),
(282, N'John Marino', N'Devils', N'6', N'D', N'R', 26, 2022, N'Easton, Massachusetts', N'Canada'),
(283, N'Michael McLeod', N'Devils', N'20', N'C', N'R', 25, 2016, N'Mississauga, Ontario', N'United States'),
(284, N'Timo Meier', N'Devils', N'96', N'LW', N'L', 26, 2023, N'Herisau, Switzerland', N'Russia'),
(285, N'Dawson Mercer', N'Devils', N'91', N'C', N'R', 21, 2020, N'Bay Roberts, Newfoundland', N'United States'),
(286, N'Colin Miller', N'Devils', N'24', N'D', N'R', 30, 2023, N'Sault Ste. Marie, Ontario', N'United States'),
(287, N'Simon Nemec', N'Devils', N'5', N'D', N'R', 19, 2022, N'LiptovskÃ½ MikulÃ¡Å¡, Slovakia', N'Canada'),
(288, N'Tomas Nosek', N'Devils', N'92', N'C', N'L', 31, 2023, N'Pardubice, Czechoslovakia', N'France'),
(289, N'Ondrej PalatÂ (A)', N'Devils', N'18', N'LW', N'L', 32, 2022, N'FrÃ½dek-MÃ­stek, Czechoslovakia', N'United States'),
(290, N'Akira Schmid', N'Devils', N'40', N'G', N'L', 23, 2018, N'Bern, Switzerland', N'Injured Reserve'),
(291, N'Jonas Siegenthaler', N'Devils', N'71', N'D', N'L', 26, 2021, N'ZÃ¼rich, Switzerland', N'Canada'),
(292, N'Brendan Smith', N'Devils', N'2', N'D', N'L', 34, 2022, N'Etobicoke, Ontario', N'Canada'),
(293, N'Tyce Thompson', N'Devils', N'12', N'C', N'R', 24, 2019, N'Oyster Bay, New York', N'Sweden'),
(294, N'Chris Tierney', N'Devils', N'67', N'C', N'L', 29, 2023, N'Keswick, Ontario', N'Canada'),
(295, N'Tyler Toffoli', N'Devils', N'73', N'RW', N'R', 31, 2023, N'Scarborough, Ontario', N'Canada'),
(296, N'Vitek Vanecek', N'Devils', N'41', N'G', N'L', 27, 2022, N'HavlÃ­ÄkÅ¯v Brod, Czech Republic', N'Canada'),
(297, N'Topias Vilen', N'Devils', N'83', N'D', N'L', 20, 2021, N'Lahti, Finland', N'Canada'),
(298, N'Sebastian Aho', N'Islanders', N'25', N'D', N'L', 27, 2017, N'UmeÃ¥, Sweden', N'United States'),
(299, N'Mathew Barzal', N'Islanders', N'13', N'C', N'R', 26, 2015, N'Coquitlam, British Columbia', N'Canada'),
(300, N'Samuel Bolduc', N'Islanders', N'4', N'D', N'L', 22, 2019, N'Laval, Quebec', N'Finland'),
(301, N'Casey Cizikas', N'Islanders', N'53', N'C', N'L', 32, 2009, N'Toronto, Ontario', N'Switzerland'),
(302, N'Cal ClutterbuckÂ (A)', N'Islanders', N'15', N'RW', N'R', 35, 2013, N'Welland, Ontario', N'Sweden'),
(303, N'Noah Dobson', N'Islanders', N'8', N'D', N'R', 23, 2018, N'Summerside, Prince Edward Island', N'United States'),
(304, N'Pierre Engvall', N'Islanders', N'18', N'LW', N'L', 27, 2023, N'Ljungby, Sweden', N'United States'),
(305, N'Hudson Fasching', N'Islanders', N'20', N'RW', N'R', 28, 2022, N'Milwaukee, Wisconsin', N'Canada'),
(306, N'Julien Gauthier', N'Islanders', N'77', N'RW', N'R', 25, 2023, N'Pointe-aux-Trembles, Quebec', N'United States'),
(307, N'Simon Holmstrom', N'Islanders', N'10', N'RW', N'L', 22, 2019, N'Tranas, Sweden', N'Canada'),
(308, N'Bo Horvat', N'Islanders', N'14', N'C', N'L', 28, 2023, N'Rodney, Ontario', N'Switzerland'),
(309, N'Ross Johnston', N'Islanders', N'32', N'LW', N'L', 29, 2015, N'Charlottetown, Prince Edward Island', N'Canada'),
(310, N'Karson Kuhlman', N'Islanders', N'20', N'C', N'R', 27, 2023, N'Esko, Minnesota', N'Canada'),
(311, N'Anders LeeÂ (C)', N'Islanders', N'27', N'LW', N'L', 33, 2009, N'Edina, Minnesota', N'Slovakia'),
(312, N'Matt Martin', N'Islanders', N'17', N'LW', N'L', 34, 2018, N'Windsor, Ontario', N'Czech Republic'),
(313, N'Scott Mayfield', N'Islanders', N'24', N'D', N'R', 30, 2011, N'St. Louis, Missouri', N'Czech Republic'),
(314, N'Brock Nelson', N'Islanders', N'29', N'LW', N'L', 31, 2010, N'Warroad, Minnesota', N'Switzerland'),
(315, N'Jean-Gabriel Pageau', N'Islanders', N'44', N'C', N'R', 30, 2020, N'Ottawa, Ontario', N'Switzerland'),
(316, N'Kyle Palmieri', N'Islanders', N'21', N'RW', N'R', 32, 2021, N'Smithtown, New York', N'Canada'),
(317, N'Zach PariseÂ (UFA)', N'Islanders', N'11', N'LW', N'L', 39, 2021, N'Minneapolis, Minnesota', N'United States'),
(318, N'Adam Pelech', N'Islanders', N'3', N'D', N'L', 29, 2012, N'Toronto, Ontario', N'Canada'),
(319, N'Ryan Pulock', N'Islanders', N'6', N'D', N'R', 28, 2013, N'Grandview, Manitoba', N'Canada'),
(320, N'Alexander Romanov', N'Islanders', N'28', N'D', N'L', 23, 2022, N'Moscow, Russia', N'Czech Republic'),
(321, N'Cory SchneiderÂ (UFA)', N'Islanders', N'35', N'G', N'L', 37, 2021, N'Marblehead, Massachusetts', N'Finland'),
(322, N'Jakub Skarek', N'Islanders', N'1', N'G', N'L', 23, 2018, N'Jihlava, Czech Republic', N'Sweden'),
(323, N'Ilya Sorokin', N'Islanders', N'30', N'G', N'L', 28, 2014, N'Mezhdurechensk, Russia', N'Canada'),
(324, N'Semyon Varlamov', N'Islanders', N'40', N'G', N'L', 35, 2019, N'Kuybyshev, Soviet Union', N'Canada'),
(325, N'Oliver WahlstromÂ ', N'Islanders', N'26', N'RW', N'R', 23, 2018, N'Yarmouth, Maine', N'Canada'),
(326, N'Alex Belzile', N'Rangers', N'â€“', N'RW', N'R', 32, 2023, N'Saint-Eloi, Quebec', N'Canada'),
(327, N'Nick Bonino', N'Rangers', N'â€“', N'C', N'L', 35, 2023, N'Hartford, Connecticut', N'Canada'),
(328, N'Filip Chytil', N'Rangers', N'72', N'C', N'L', 24, 2017, N'KromÄ›Å™Ã­Å¾, Czech Republic', N'Sweden'),
(329, N'Adam Fox', N'Rangers', N'23', N'D', N'R', 25, 2019, N'Jericho, New York', N'United States'),
(330, N'Barclay GoodrowÂ (A)', N'Rangers', N'21', N'C', N'L', 30, 2021, N'Toronto, Ontario', N'Canada'),
(331, N'Erik Gustafsson', N'Rangers', N'â€“', N'D', N'L', 31, 2023, N'NynÃ¤shamn,Â Sweden', N'Sweden'),
(332, N'Ben Harpur', N'Rangers', N'5', N'D', N'L', 28, 2022, N'Hamilton, Ontario', N'Canada'),
(333, N'Kaapo Kakko', N'Rangers', N'24', N'RW', N'L', 22, 2019, N'Turku, Finland', N'Canada'),
(334, N'Chris KreiderÂ (A)', N'Rangers', N'20', N'LW', N'L', 32, 2009, N'Boxford, Massachusetts', N'United States'),
(335, N'Alexis Lafreniere', N'Rangers', N'13', N'LW', N'L', 21, 2020, N'Saint-Eustache, Quebec', N'United States'),
(336, N'Ryan Lindgren', N'Rangers', N'55', N'D', N'L', 25, 2018, N'Minneapolis, Minnesota', N'Canada'),
(337, N'Connor Mackey', N'Rangers', N'â€“', N'D', N'L', 26, 2023, N'Tower Lakes, Illinois', N'United States'),
(338, N'K''Andre Miller', N'Rangers', N'79', N'D', N'L', 23, 2018, N'Saint Paul, Minnesota', N'United States'),
(339, N'Artemi PanarinÂ (A)', N'Rangers', N'10', N'LW', N'R', 31, 2019, N'Korkino, Soviet Union', N'Canada'),
(340, N'Tyler Pitlick', N'Rangers', N'â€“', N'C', N'R', 31, 2023, N'Minneapolis, Minnesota', N'United States'),
(341, N'Jonathan Quick', N'Rangers', N'32', N'G', N'L', 37, 2023, N'Milford, Connecticut', N'United States'),
(342, N'Braden Schneider', N'Rangers', N'4', N'D', N'R', 21, 2020, N'Prince Albert, Saskatchewan', N'Canada'),
(343, N'Igor Shesterkin', N'Rangers', N'31', N'G', N'L', 27, 2014, N'Moscow, Russia', N'Canada'),
(344, N'Vincent Trocheck', N'Rangers', N'16', N'C', N'R', 30, 2022, N'Pittsburgh, Pennsylvania', N'Russia'),
(345, N'Jacob TroubaÂ (C)', N'Rangers', N'8', N'D', N'R', 29, 2019, N'Rochester, Michigan', N'United States'),
(346, N'Jimmy Vesey', N'Rangers', N'26', N'LW', N'L', 30, 2022, N'Boston, Massachusetts', N'Czech Republic'),
(347, N'Blake Wheeler', N'Rangers', N'17', N'RW', N'R', 37, 2023, N'Plymouth, Minnesota', N'Russia'),
(348, N'Mika ZibanejadÂ (A)', N'Rangers', N'93', N'C', N'R', 30, 2016, N'Huddinge, Sweden', N'Russia'),
(349, N'Wade Allison', N'Flyers', N'17', N'RW', N'R', 25, 2016, N'Myrtle, Manitoba', N'United States'),
(350, N'Cam AtkinsonÂ ', N'Flyers', N'89', N'RW', N'R', 34, 2021, N'Riverside, Connecticut', N'Injured Reserve'),
(351, N'Noah Cates', N'Flyers', N'27', N'LW', N'L', 24, 2017, N'Stillwater, Minnesota', N'Canada'),
(352, N'Sean CouturierÂ (A)Â ', N'Flyers', N'14', N'C', N'L', 30, 2011, N'Phoenix, Arizona', N'United States'),
(353, N'Nicolas Deslauriers', N'Flyers', N'44', N'LW', N'L', 32, 2022, N'LaSalle, Quebec', N'Czech Republic'),
(354, N'Ryan EllisÂ ', N'Flyers', N'94', N'D', N'R', 32, 2021, N'Hamilton, Ontario', N'United States'),
(355, N'Joel Farabee', N'Flyers', N'86', N'LW', N'L', 23, 2018, N'Cicero, New York', N'Canada'),
(356, N'Morgan Frost', N'Flyers', N'48', N'C', N'L', 24, 2017, N'Aurora, Ontario', N'Sweden'),
(357, N'Carter Hart', N'Flyers', N'79', N'G', N'L', 25, 2016, N'Sherwood Park, Alberta', N'Canada'),
(358, N'Garnet Hathaway', N'Flyers', N'19', N'RW', N'R', 31, 2023, N'Naples, Florida', N'Finland'),
(359, N'Travis Konecny', N'Flyers', N'11', N'RW', N'R', 26, 2015, N'London, Ontario', N'United States'),
(360, N'Tanner Laczynski', N'Flyers', N'58', N'C', N'R', 26, 2016, N'Shorewood, Illinois', N'Canada'),
(361, N'Scott LaughtonÂ (A)', N'Flyers', N'21', N'C', N'L', 29, 2012, N'Oakville, Ontario', N'United States'),
(362, N'Cal Petersen', N'Flyers', N'40', N'G', N'R', 28, 2023, N'Waterloo, Iowa', N'United States'),
(363, N'Ryan Poehling', N'Flyers', N'25', N'C', N'L', 24, 2023, N'Lakeville, Minnesota', N'United States'),
(364, N'Rasmus Ristolainen', N'Flyers', N'55', N'D', N'R', 28, 2021, N'Turku, Finland', N'Russia'),
(365, N'Felix Sandstrom', N'Flyers', N'32', N'G', N'L', 26, 2015, N'GÃ¤vle, Sweden', N'United States'),
(366, N'Travis Sanheim', N'Flyers', N'6', N'D', N'L', 27, 2014, N'Elkhorn, Manitoba', N'United States'),
(367, N'Nick Seeler', N'Flyers', N'24', N'D', N'L', 30, 2021, N'Eden Prairie, Minnesota', N'Canada'),
(368, N'Marc Staal', N'Flyers', N'18', N'D', N'L', 36, 2023, N'Thunder Bay, Ontario', N'Russia'),
(369, N'Owen Tippett', N'Flyers', N'74', N'RW', N'R', 24, 2022, N'Peterborough, Ontario', N'United States'),
(370, N'Sean Walker', N'Flyers', N'26', N'D', N'R', 28, 2023, N'Keswick, Ontario', N'United States'),
(371, N'Cameron York', N'Flyers', N'8', N'D', N'L', 22, 2019, N'Anaheim, California', N'United States'),
(372, N'Noel Acciari', N'Penguins', N'55', N'C', N'R', 31, 2023, N'Johnston, Rhode Island', N'United States'),
(373, N'Jeff Carter', N'Penguins', N'77', N'C', N'R', 38, 2021, N'London, Ontario', N'Sweden'),
(374, N'Sidney CrosbyÂ (C)', N'Penguins', N'87', N'C', N'L', 36, 2005, N'Cole Harbour, Nova Scotia', N'Canada'),
(375, N'Lars Eller', N'Penguins', N'20', N'C', N'L', 34, 2023, N'RÃ¸dovre, Denmark', N'United States'),
(376, N'Ryan Graves', N'Penguins', N'27', N'D', N'L', 28, 2023, N'Yarmouth, Nova Scotia', N'Injured Reserve'),
(377, N'Jake Guentzel', N'Penguins', N'59', N'LW', N'L', 28, 2013, N'Omaha, Nebraska', N'United States'),
(378, N'Libor HajekÂ (PTO)', N'Penguins', N'â€“', N'D', N'L', 25, 2018, N'SmrÄek, Czech Republic', N'Canada'),
(379, N'Vinnie Hinostroza', N'Penguins', N'13', N'C', N'L', 29, 2023, N'Melrose Park, Illinois', N'Injured Reserve'),
(380, N'Tristan Jarry', N'Penguins', N'35', N'G', N'L', 28, 2013, N'Surrey, British Columbia', N'Canada'),
(381, N'Andreas Johnsson', N'Penguins', N'18', N'LW', N'L', 28, 2023, N'GÃ¤vle, Sweden', N'Canada'),
(382, N'Pierre-Olivier Joseph', N'Penguins', N'73', N'D', N'L', 24, 2019, N'Laval, Quebec', N'Injured Reserve'),
(383, N'Erik Karlsson', N'Penguins', N'65', N'D', N'R', 33, 2023, N'Landsbro, Sweden', N'United States'),
(384, N'Kris LetangÂ (A)', N'Penguins', N'58', N'D', N'R', 36, 2005, N'Montreal, Quebec', N'Canada'),
(385, N'Evgeni MalkinÂ (A)', N'Penguins', N'71', N'C', N'L', 37, 2004, N'Magnitogorsk, Soviet Union', N'Canada'),
(386, N'Alex Nedeljkovic', N'Penguins', N'39', N'G', N'L', 27, 2023, N'Parma, Ohio', N'United States'),
(387, N'Matt Nieto', N'Penguins', N'83', N'LW', N'L', 30, 2023, N'Long Beach, California', N'Canada'),
(388, N'Alexander Nylander', N'Penguins', N'11', N'RW', N'R', 25, 2022, N'Calgary, Alberta', N'United States'),
(389, N'Drew O''Connor', N'Penguins', N'10', N'LW', N'L', 25, 2020, N'Chatham, New Jersey', N'Canada'),
(390, N'Marcus PetterssonÂ ', N'Penguins', N'28', N'D', N'L', 27, 2018, N'SkellefteÃ¥, Sweden', N'United States'),
(391, N'Rem Pitlick', N'Penguins', N'16', N'C', N'L', 26, 2023, N'Ottawa, Ontario', N'United States'),
(392, N'Austin WagnerÂ (PTO)', N'Penguins', N'â€“', N'LW', N'L', 26, 2023, N'Calgary, Alberta', N'Finland'),
(393, N'Alexander Alexeyev', N'Capitals', N'27', N'D', N'L', 23, 2018, N'St. Petersburg, Russia', N'Sweden'),
(394, N'Nicolas Aube-Kubel', N'Capitals', N'96', N'RW', N'R', 27, 2022, N'Slave Lake, Alberta', N'Canada'),
(395, N'Nicklas BackstromÂ (A)', N'Capitals', N'19', N'C', N'L', 35, 2006, N'GÃ¤vle, Sweden', N'United States'),
(396, N'John CarlsonÂ (A)', N'Capitals', N'74', N'D', N'R', 33, 2008, N'Natick, Massachusetts', N'Canada'),
(397, N'Nic Dowd', N'Capitals', N'26', N'C', N'R', 33, 2018, N'Huntsville, Alabama', N'Canada'),
(398, N'Joel Edmundson', N'Capitals', N'6', N'D', N'L', 30, 2023, N'Brandon, Manitoba', N'Canada'),
(399, N'Martin Fehervary', N'Capitals', N'42', N'D', N'L', 23, 2018, N'Bratislava, Slovakia', N'United States'),
(400, N'Nick Jensen', N'Capitals', N'3', N'D', N'R', 32, 2019, N'Rogers, Minnesota', N'United States'),
(401, N'Darcy Kuemper', N'Capitals', N'35', N'G', N'L', 33, 2022, N'Saskatoon, Saskatchewan', N'Canada'),
(402, N'Evgeny Kuznetsov', N'Capitals', N'92', N'C', N'L', 31, 2010, N'Chelyabinsk, Russia', N'Canada'),
(403, N'Charlie Lindgren', N'Capitals', N'79', N'G', N'R', 29, 2022, N'Lakeville, Minnesota', N'Denmark'),
(404, N'Anthony Mantha', N'Capitals', N'39', N'RW', N'L', 28, 2021, N'Longueuil, Quebec', N'Canada'),
(405, N'Sonny Milano', N'Capitals', N'15', N'LW', N'L', 27, 2022, N'Massapequa, New York', N'United States'),
(406, N'T. J. Oshie', N'Capitals', N'77', N'RW', N'R', 36, 2015, N'Mount Vernon, Washington', N'Czech Republic'),
(407, N'Alexander OvechkinÂ (C)', N'Capitals', N'8', N'LW', N'R', 37, 2004, N'Moscow, Soviet Union', N'United States'),
(408, N'Max PaciorettyÂ ', N'Capitals', N'67', N'LW', N'L', 34, 2023, N'New Canaan, Connecticut', N'Canada'),
(409, N'Matthew Phillips', N'Capitals', N'â€“', N'RW', N'R', 25, 2023, N'Calgary, Alberta', N'Sweden'),
(411, N'Rasmus Sandin', N'Capitals', N'38', N'D', N'L', 23, 2023, N'Uppsala, Sweden', N'Sweden'),
(412, N'Dylan Strome', N'Capitals', N'17', N'C', N'L', 26, 2022, N'Mississauga, Ontario', N'Canada'),
(413, N'Trevor van Riemsdyk', N'Capitals', N'57', N'D', N'R', 32, 2020, N'Middletown, New Jersey', N'Russia'),
(414, N'Tom Wilson', N'Capitals', N'43', N'RW', N'R', 29, 2012, N'Toronto, Ontario', N'United States'),
(615, N'AB Grier', N'Bruins', N'13', N'LF', N'L', 33, 0, N'Anywhere', N'Canada'),
(621, N'AB Grier', N'Bruins', N'13', N'LW', N'L', 33, 0, N'Anywhere', N'Canada'),
(622, N'John Doe', N'Bruins & Co.', N'13', N'LW', N'L', 33, 0, N'Toronto, ON', N'Canada'),
(623, N'John Doe', N'Bruins & Co.', N'13', N'LW', N'L', 33, 0, N'Toronto, ON', N'Canada'),
(716, N'Connor McDavid', N'Oilers', N'97', N'C', N'L', 26, 1, N'Richmond Hill', N'Canada'),
(717, N'Sidney Crosby', N'Penguins', N'87', N'C', N'L', 36, 1, N'Halifax', N'Canada'),
(718, N'Alexander Ovechkin', N'Capitals', N'8', N'LW', N'R', 38, 1, N'Moscow', N'Russia'),
(719, N'Ambidextrous Player', N'Bruins', N'99', N'C', N'B', 25, 1, N'Boston', N'USA'),
(720, N'Ambidextrous Player', N'Bruins', N'99', N'C', N'B', 25, 1, N'Boston', N'USA'),
(815, N'A. J. Greer', N'Bruins', N'23', N'F', N'R', 26, 2021, N'nowhere at all', N'Canada'),
(816, N'A. J. Greer', N'Bruins', N'23', N'G', N'R', 26, 2021, N'nowhere at all', N'Canada'),
(817, N'A. J. Greer', N'Bruins', N'23', N'F', N'R', 26, 2021, N'nowhere at all', N'Canada')
GO
SET IDENTITY_INSERT [NHL].[Roster] OFF
GO
declare @status varchar(100);
SELECT @status='NHL.Roster FINISHED! Volume=' + convert(varchar(100), count(*)) + '. Timestamp:' + convert(varchar(50), getdate(), 120) from NHL.Roster;
print @status;
GO

SET NOEXEC OFF;
GO
