name: Execute Azure SQL Code

on:
  push:
    branches:
      - main

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the full history to ensure HEAD~1 is valid

      # Step 2: Install SQL tools
      - name: Install SQL tools
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      # Step 3: Detect changed SQL files and execute them
      - name: Execute changed SQL scripts
        env:
          AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
        run: |
          # Get the list of changed files
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)
          else
            # If no previous commit, consider all files in the repository
            CHANGED_FILES=$(git ls-files)
          fi

          # Filter for .sql files and execute them
          for file in $CHANGED_FILES; do
            if [[ $file == *.sql ]]; then
              echo "Executing $file"
              /opt/mssql-tools/bin/sqlcmd -S $AZURE_SQL_SERVER -d $AZURE_SQL_DATABASE -U $AZURE_SQL_USER -P $AZURE_SQL_PASSWORD -i "$file"
            fi
          done
